// AGENCIES 
export const GET_AGENCIES = 'GET_AGENCIES'
export const DELETE_AGENCY = 'DELETE_AGENCY'
export const ADD_AGENCY = 'ADD_AGENCY'
export const UPDATE_AGENCY = 'UPDATE_AGENCY'

// PHOTOGRAPHERS
export const GET_PHOTOGRAPHERS = 'GET_PHOTOGRAPHERS'
export const DELETE_PHOTOGRAPHER = 'DELETE_PHOTOGRAPHER'
export const ADD_PHOTOGRAPHER = 'ADD_PHOTOGRAPHER'
export const UPDATE_PHOTOGRAPHER = 'UPDATE_PHOTOGRAPHER' 

// GOALS 
export const GET_GOALS = 'GET_GOALS'
export const DELETE_GOAL = 'DELETE_GOAL'
export const ADD_GOAL = 'ADD_GOAL'
export const UPDATE_GOAL = 'UPDATE_PHOTOGRAPHER' 

// USER AUTH 
export const USER_LOADING = 'USER_LOADING'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'