// AGENCIES 
export const GET_AGENCIES = 'GET_AGENCIES'
export const DELETE_AGENCY = 'DELETE_AGENCY'
export const ADD_AGENCY = 'ADD_AGENCY'
export const UPDATE_AGENCY = 'UPDATE_AGENCY'

// PHOTOGRAPHERS
export const GET_PHOTOGRAPHERS = 'GET_PHOTOGRAPHERS'
export const DELETE_PHOTOGRAPHER = 'DELETE_PHOTOGRAPHER'
export const ADD_PHOTOGRAPHER = 'ADD_PHOTOGRAPHER'
export const UPDATE_PHOTOGRAPHER = 'UPDATE_PHOTOGRAPHER' 

// GOALS 
export const GET_GOALS = 'GET_GOALS'
export const DELETE_GOAL = 'DELETE_GOAL'
export const ADD_GOAL = 'ADD_GOAL'
export const UPDATE_GOAL = 'UPDATE_PHOTOGRAPHER' 